import type { Mosque, Teacher, Student, Schedule } from "../types";

export const mosques: Mosque[] = [
  { id:1, name:"أبو بكر الصديق", municipality:"الأغواط", imam:"", teachersCount:4, studentsCount:0, progress:59 },
  { id:2, name:"أبو عبيدة الجراح", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:68 },
  { id:3, name:"أحمد بن حنبل", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:77 },
  { id:4, name:"أحمد حماني", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:86 },
  { id:5, name:"أحمد شطة", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:95 },
  { id:6, name:"أسامة بن زيد", municipality:"الأغواط", imam:"", teachersCount:5, studentsCount:0, progress:56 },
  { id:7, name:"الأمير خالد", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:65 },
  { id:8, name:"الأمير عبد القادر", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:74 },
  { id:9, name:"الامام مالك", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:83 },
  { id:10, name:"الامام مسلم", municipality:"الأغواط", imam:"", teachersCount:4, studentsCount:0, progress:92 },
  { id:11, name:"الامير عبد القادر", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:53 },
  { id:12, name:"البدر", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:62 },
  { id:13, name:"البركة", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:71 },
  { id:14, name:"الحسين", municipality:"الأغواط", imam:"", teachersCount:4, studentsCount:0, progress:80 },
  { id:15, name:"الخليفة", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:89 },
  { id:16, name:"الرحمن", municipality:"الأغواط", imam:"", teachersCount:6, studentsCount:0, progress:50 },
  { id:17, name:"الريان", municipality:"الأغواط", imam:"", teachersCount:4, studentsCount:0, progress:59 },
  { id:18, name:"الشاذولية", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:68 },
  { id:19, name:"الشهداء", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:77 },
  { id:20, name:"الشيخ البشير الابراهيمي", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:16, progress:86 },
  { id:21, name:"الصحوة", municipality:"الأغواط", imam:"", teachersCount:5, studentsCount:0, progress:95 },
  { id:22, name:"العتيق", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:56 },
  { id:23, name:"القدس", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:65 },
  { id:24, name:"الكبير", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:74 },
  { id:25, name:"الكوثر", municipality:"الأغواط", imam:"", teachersCount:5, studentsCount:0, progress:83 },
  { id:26, name:"المدرسة القرآنية سماح", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:92 },
  { id:27, name:"النور(تاوتي)", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:53 },
  { id:28, name:"الهدى", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:62 },
  { id:29, name:"بلال بن رباح", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:71 },
  { id:30, name:"جابر بن عبد الله", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:80 },
  { id:31, name:"حذيفة بن اليمان", municipality:"الأغواط", imam:"", teachersCount:5, studentsCount:0, progress:89 },
  { id:32, name:"زيد بن ثابت", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:50 },
  { id:33, name:"سيدنا أبوهريرة", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:59 },
  { id:34, name:"سيدنا حمزة", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:68 },
  { id:35, name:"سيدي الشيخ", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:77 },
  { id:36, name:"سيدي عبد القادر جيلالي", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:86 },
  { id:37, name:"طيب الحيرش", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:95 },
  { id:38, name:"عائشة أم المؤمنين", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:56 },
  { id:39, name:"عبد الله بن عمر", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:0, progress:65 },
  { id:40, name:"عثمان بن عفان", municipality:"الأغواط", imam:"", teachersCount:6, studentsCount:0, progress:74 },
  { id:41, name:"عقبة بن نافع", municipality:"الأغواط", imam:"", teachersCount:9, studentsCount:0, progress:83 },
  { id:42, name:"علي بن أبي طالب", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:26, progress:92 },
  { id:43, name:"عمر بن الخطاب", municipality:"الأغواط", imam:"", teachersCount:4, studentsCount:0, progress:53 },
  { id:44, name:"فاطمة الزهراء", municipality:"الأغواط", imam:"", teachersCount:5, studentsCount:0, progress:62 },
  { id:45, name:"م.ق.سيدي عبد القادر الجيلالي", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:71 },
  { id:46, name:"مبارك الميلي", municipality:"الأغواط", imam:"", teachersCount:2, studentsCount:0, progress:80 },
  { id:47, name:"مبروك كويسي", municipality:"الأغواط", imam:"", teachersCount:3, studentsCount:48, progress:89 },
  { id:48, name:"مدرسة الشيخ محمد عزوز", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:50 },
  { id:49, name:"مصعب بن عمير", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:59 },
  { id:50, name:"مصلى ابو هريرة", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:68 },
  { id:51, name:"مصلى عقبة بن نافع", municipality:"الأغواط", imam:"", teachersCount:1, studentsCount:0, progress:77 },
];

export const teachers: Teacher[] = [
  { id:1, name:"محمد الأخضر لعروسي", rank:"مفتش إدارة الأملاك الوقفية", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"المديرية" },
  { id:2, name:"بلقاسم جيلاني", rank:"إمام أستاذ رئيسي", role:"موظف", dob:"1974/08/13", education:"جامعي", generation:"", phone:"06 69 34 74 16", municipality:"الأغواط", mosqueId:6, mosqueName:"أسامة بن زيد" },
  { id:3, name:"عبد القادر كيرد", rank:"إمام أستاذ رئيسي", role:"موظف", dob:"1967/11/01", education:"ثالثة ثانوي", generation:"6", phone:"06 60 41 25 25", municipality:"الأغواط", mosqueId:4, mosqueName:"أحمد حماني" },
  { id:4, name:"صفي الدين الذيب", rank:"إمام أستاذ رئيسي", role:"موظف", dob:"1978/05/28", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:35, mosqueName:"سيدي الشيخ" },
  { id:5, name:"عبد السلام بن جدو", rank:"إمام أستاذ رئيسي", role:"موظف", dob:"1975/08/24", education:"جامعي", generation:"", phone:"07 78 73 27 40", municipality:"الأغواط", mosqueId:40, mosqueName:"عثمان بن عفان" },
  { id:6, name:"الأخضر عبد الحفيظي", rank:"إمام أستاذ", role:"موظف", dob:"1965", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:46, mosqueName:"مبارك الميلي" },
  { id:7, name:"عمر محمدي", rank:"إمام أستاذ", role:"موظف", dob:"1975/12/02", education:"جامعي", generation:"4", phone:"06 64 32 66 86", municipality:"الأغواط", mosqueId:27, mosqueName:"النور(تاوتي)" },
  { id:8, name:"قويدر مرزوقي", rank:"إمام أستاذ", role:"موظف", dob:"1970/12/03", education:"جامعي", generation:"4", phone:"06 68 44 23 32", municipality:"الأغواط", mosqueId:25, mosqueName:"الكوثر" },
  { id:9, name:"قويدر ميلودية", rank:"إمام أستاذ", role:"موظف", dob:"1975/06/15", education:"جامعي", generation:"6", phone:"06 62 16 40 40", municipality:"الأغواط", mosqueId:5, mosqueName:"أحمد شطة" },
  { id:10, name:"سعيد بن مويزة", rank:"إمام أستاذ", role:"موظف", dob:"1979/09/25", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:23, mosqueName:"القدس" },
  { id:11, name:"عبد الباقي عبد الباقي", rank:"إمام أستاذ", role:"موظف", dob:"1971/06/11", education:"جامعي", generation:"", phone:"", municipality:"الاغواط", mosqueId:9, mosqueName:"الامام مالك" },
  { id:12, name:"عبد القادر بوزيد", rank:"إمام أستاذ", role:"موظف", dob:"1979/08/30", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:32, mosqueName:"زيد بن ثابت" },
  { id:13, name:"ياسين صادقي", rank:"إمام مدرس", role:"موظف", dob:"1980/11/22", education:"جامعي", generation:"3", phone:"06 68 44 16 44", municipality:"الأغواط", mosqueId:10, mosqueName:"الامام مسلم" },
  { id:14, name:"العربي موسلي", rank:"إمام أستاذ", role:"موظف", dob:"197/04/08", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:24, mosqueName:"الكبير" },
  { id:15, name:"احمد  فنطازي", rank:"إمام أستاذ", role:"موظف", dob:"1986/10/26", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:19, mosqueName:"الشهداء" },
  { id:16, name:"العلمي غويرق", rank:"إمام أستاذ", role:"موظف", dob:"1969/25/07", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:17, mosqueName:"الريان" },
  { id:17, name:"علي  بساس", rank:"إمام أستاذ", role:"موظف", dob:"1983/05/15", education:"", generation:"", phone:"06 98 08 76 59", municipality:"الأغواط", mosqueId:38, mosqueName:"عائشة أم المؤمنين" },
  { id:18, name:"جلول عاجب", rank:"إمام أستاذ", role:"موظف", dob:"1974/05/03", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:44, mosqueName:"فاطمة الزهراء" },
  { id:19, name:"منذر شلاوشي", rank:"إمام أستاذ", role:"موظف", dob:"1993/02/08", education:"جامعي", generation:"1", phone:"06 57 77 78 09", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:20, name:"عبد اللطيف كادي", rank:"إمام أستاذ", role:"موظف", dob:"1993/11/13", education:"جامعي", generation:"", phone:"", municipality:"الاغواط", mosqueId:13, mosqueName:"البركة" },
  { id:21, name:"عبد القادر رزيقي", rank:"إمام أستاذ", role:"موظف", dob:"1954/12/16", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"أبو بكر الصديق" },
  { id:22, name:"محمد قحقوحي", rank:"إمام أستاذ", role:"موظف", dob:"1972/07/21", education:"جامعي", generation:"", phone:"06 99 29 07 94", municipality:"الأغواط", mosqueId:28, mosqueName:"الهدى" },
  { id:23, name:"مختار بعيط", rank:"إمام أستاذ", role:"موظف", dob:"1986/10/8", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:4, mosqueName:"أحمد حماني" },
  { id:24, name:"نصر الدين  قميتي", rank:"إمام أستاذ", role:"موظف", dob:"1993/02/15", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:23, mosqueName:"القدس" },
  { id:25, name:"سعد بعيطيش", rank:"إمام أستاذ", role:"موظف", dob:"23-02-1982", education:"", generation:"", phone:"06 99 27 77 82", municipality:"الأغواط", mosqueId:31, mosqueName:"حذيفة بن اليمان" },
  { id:26, name:"عبد الفتاح ماضوي", rank:"إمام أستاذ", role:"موظف", dob:"1995/05/3", education:"جامعي", generation:"", phone:"06 67 03 54 59", municipality:"الأغواط", mosqueId:29, mosqueName:"بلال بن رباح" },
  { id:27, name:"يوسف مسعودي", rank:"إمام أستاذ", role:"موظف", dob:"1985/09/28", education:"جامعي", generation:"", phone:"06 76 88 91 75", municipality:"الأغواط", mosqueId:34, mosqueName:"سيدنا حمزة" },
  { id:28, name:"يحيى غويرق", rank:"إمام أستاذ", role:"موظف", dob:"1986/09/27", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:21, mosqueName:"الصحوة" },
  { id:29, name:"العيد كحللش", rank:"إمام أستاذ", role:"موظف", dob:"1990/07/03", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:2, mosqueName:"أبو عبيدة الجراح" },
  { id:30, name:"مصطفى بلمغربي", rank:"إمام أستاذ", role:"موظف", dob:"1935", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:15, mosqueName:"الخليفة" },
  { id:31, name:"لحسن طيفوري", rank:"إمام أستاذ", role:"موظف", dob:"1965", education:"", generation:"5", phone:"07 74 35 27 53", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:32, name:"نفيسة بدراني", rank:"مرشدة دينية رئيسية", role:"موظف", dob:"1967/03/20", education:"جامعي", generation:"2", phone:"06 69 92 02 00", municipality:"الأغواط", mosqueId:40, mosqueName:"عثمان بن عفان" },
  { id:33, name:"مفيدة خنافيف", rank:"مرشدة دينية رئيسية", role:"موظف", dob:"1984/08/10", education:"جامعي", generation:"2", phone:"06 58 66 77 24", municipality:"الأغواط", mosqueId:31, mosqueName:"حذيفة بن اليمان" },
  { id:34, name:"سمية بن رحال", rank:"مرشدة دينية رئيسية", role:"موظف", dob:"1975/08/22", education:"جامعي", generation:"", phone:"06 97 29 42 66", municipality:"الأغواط", mosqueId:23, mosqueName:"القدس" },
  { id:35, name:"دلال بن غربي", rank:"مرشدة دينية", role:"موظف", dob:"1984/02/09", education:"جامعي", generation:"4", phone:"06 73 35 35 18", municipality:"الأغواط", mosqueId:3, mosqueName:"أحمد بن حنبل" },
  { id:36, name:"بن مويزة مريم", rank:"مرشدة دينية", role:"موظف", dob:"1989/09/24", education:"جامعي", generation:"", phone:"06 98 20 90 04", municipality:"الأغواط", mosqueId:37, mosqueName:"طيب الحيرش" },
  { id:37, name:"كعبوش  أمينة", rank:"مرشدة دينية", role:"موظف", dob:"1992/04/30", education:"جامعي", generation:"3", phone:"06 73 74 97 60", municipality:"الأغواط", mosqueId:10, mosqueName:"الامام مسلم" },
  { id:38, name:"رميصاء لجدل", rank:"مرشدة دينية", role:"موظف", dob:"1986/03/22", education:"جامعي", generation:"", phone:"06 63 76 48 15", municipality:"الأغواط", mosqueId:14, mosqueName:"الحسين" },
  { id:39, name:"بونيف نعيمة", rank:"مرشدة دينية", role:"موظف", dob:"1985/01/08", education:"جامعي", generation:"3", phone:"06 69 30 43 03", municipality:"الأغواط", mosqueId:33, mosqueName:"سيدنا أبوهريرة" },
  { id:40, name:"بساس مارية", rank:"مرشدة دينية", role:"موظف", dob:"1990/11/26", education:"جامعي", generation:"2", phone:"06 67 25 63 55", municipality:"الأغواط", mosqueId:39, mosqueName:"عبد الله بن عمر" },
  { id:41, name:"بساس أسيا", rank:"مرشدة دينية", role:"موظف", dob:"1989/09/01", education:"جامعي", generation:"1", phone:"06 67 45 74 36", municipality:"الأغواط", mosqueId:19, mosqueName:"الشهداء" },
  { id:42, name:"بعيط حليمة", rank:"مرشدة دينية", role:"موظف", dob:"1988/10/11", education:"جامعي", generation:"3", phone:"06 64 19 82 84", municipality:"الأغواط", mosqueId:35, mosqueName:"سيدي الشيخ" },
  { id:43, name:"عرارم فاطمة الزهراء", rank:"مرشدة دينية", role:"موظف", dob:"1989/07/24", education:"جامعي", generation:"3", phone:"06 99 13 81 81", municipality:"الأغواط", mosqueId:30, mosqueName:"جابر بن عبد الله" },
  { id:44, name:"فداق زبيدة", rank:"مرشدة دينية", role:"موظف", dob:"1984/02/05", education:"جامعي", generation:"4", phone:"06 71 64 80 72", municipality:"الأغواط", mosqueId:5, mosqueName:"أحمد شطة" },
  { id:45, name:"بن السايح سناء", rank:"مرشدة دينية", role:"موظف", dob:"1992/16/01", education:"جامعي", generation:"", phone:"06 73 06 55 87", municipality:"الأغواط", mosqueId:9, mosqueName:"الامام مالك" },
  { id:46, name:"همكة حنان حسناء", rank:"مرشدة دينية", role:"موظف", dob:"1993/07/14", education:"جامعي", generation:"1", phone:"", municipality:"الأغواط", mosqueId:31, mosqueName:"حذيفة بن اليمان" },
  { id:47, name:"سعيد سبطي", rank:"إمام مدرس", role:"موظف", dob:"1954", education:"متوسط", generation:"", phone:"06 73 22 87 22", municipality:"الأغواط", mosqueId:14, mosqueName:"الحسين" },
  { id:48, name:"أحمد خطوي", rank:"إمام مدرس", role:"موظف", dob:"1987/01/02", education:"جامعي", generation:"", phone:"06 67 67 48 82", municipality:"الأغواط", mosqueId:17, mosqueName:"الريان" },
  { id:49, name:"إسماعيل رنان", rank:"إمام مدرس", role:"موظف", dob:"1990/12/11", education:"جامعي", generation:"", phone:"05 62 07 68 99", municipality:"الأغواط", mosqueId:1, mosqueName:"المديرية" },
  { id:50, name:"أحمد النية", rank:"إمام مدرس", role:"موظف", dob:"1982-12-12", education:"جامعي", generation:"", phone:"06 73 75 06 90", municipality:"الأغواط", mosqueId:43, mosqueName:"عمر بن الخطاب" },
  { id:51, name:"الجيلالي بوقرارة", rank:"إمام مدرس", role:"موظف", dob:"1970/02/09", education:"", generation:"6", phone:"06 64 60 38 36", municipality:"الأغواط", mosqueId:21, mosqueName:"الصحوة" },
  { id:52, name:"محمد شنوفي", rank:"إمام مدرس", role:"موظف", dob:"1992/02/24", education:"ثالثة ثانوي", generation:"1", phone:"06 68 14 66 69", municipality:"الأغواط", mosqueId:10, mosqueName:"الامام مسلم" },
  { id:53, name:"بن غريقة بولرباح", rank:"إمام مدرس", role:"موظف", dob:"1980/03/28", education:"جامعي", generation:"", phone:"06 69 41 86 04", municipality:"الأغواط", mosqueId:30, mosqueName:"جابر بن عبد الله" },
  { id:54, name:"معمر حمدي", rank:"إمام مدرس", role:"موظف", dob:"1973/01/29", education:"", generation:"5", phone:"", municipality:"الأغواط", mosqueId:39, mosqueName:"عبد الله بن عمر" },
  { id:55, name:"عيسى عرارم", rank:"إمام مدرس", role:"موظف", dob:"1968/03/15", education:"رابعة متوسط", generation:"5", phone:"07 95 76 43 28", municipality:"الأغواط", mosqueId:7, mosqueName:"الأمير خالد" },
  { id:56, name:"لحبيب لمنور", rank:"إمام مدرس", role:"موظف", dob:"1966/05/27", education:"ثالثة ثانوي", generation:"4", phone:"06 63 90 07 73", municipality:"الأغواط", mosqueId:16, mosqueName:"الرحمن" },
  { id:57, name:"الحاج شلابي", rank:"إمام مدرس", role:"موظف", dob:"1967/09/29", education:"", generation:"", phone:"05 53 4256 92", municipality:"الأغواط", mosqueId:1, mosqueName:"مصلى المحطة" },
  { id:58, name:"عبد الحفيظي بولنوار", rank:"إمام مدرس", role:"موظف", dob:"1983/11/11", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:3, mosqueName:"أحمد بن حنبل" },
  { id:59, name:"تناح الأمين", rank:"إمام مدرس", role:"موظف", dob:"1987/01/04", education:"جامعي", generation:"", phone:"06 98 64 55 63", municipality:"الأغواط", mosqueId:40, mosqueName:"عثمان بن عفان" },
  { id:60, name:"تواتي بن تواتي", rank:"إمام مدرس", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:16, mosqueName:"الرحمن" },
  { id:61, name:"بن نيش يوسف", rank:"إمام مدرس", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:32, mosqueName:"زيد بن ثابت" },
  { id:62, name:"عطاءالله الجودي", rank:"إمام مدرس", role:"موظف", dob:"1969/08/16", education:"ثالثة ثانوي", generation:"1", phone:"06 60 86 24 86", municipality:"الأغواط", mosqueId:14, mosqueName:"الحسين" },
  { id:63, name:"بن حرزالله بن جدو", rank:"إمام مدرس", role:"موظف", dob:"1967/17/07", education:"", generation:"", phone:"06 69 81 78 43", municipality:"الأغواط", mosqueId:28, mosqueName:"الهدى" },
  { id:64, name:"مبروك بلحوت", rank:"إمام مدرس", role:"موظف", dob:"1977/10/25", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:33, mosqueName:"سيدنا أبوهريرة" },
  { id:65, name:"خالد همكة", rank:"إمام مدرس", role:"موظف", dob:"06-08-1989", education:"ثانوي", generation:"", phone:"06 59 87 57 28", municipality:"الاغواط", mosqueId:37, mosqueName:"طيب الحيرش" },
  { id:66, name:"الحاج ارزيقي", rank:"إمام مدرس", role:"موظف", dob:"1969/10/12", education:"تقني", generation:"", phone:"06 65 91 79 17", municipality:"الأغواط", mosqueId:1, mosqueName:"المديرية" },
  { id:67, name:"عبد الحميد رزق الله", rank:"إمام مدرس", role:"موظف", dob:"1982/08/01", education:"بكالوريا", generation:"3", phone:"06 64 95 43 16", municipality:"الأغواط", mosqueId:6, mosqueName:"أسامة بن زيد" },
  { id:68, name:"حليمة السعدية معيلب", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"02-12-1988", education:"جامعي", generation:"2", phone:"06 99 27 91 90", municipality:"الأغواط", mosqueId:42, mosqueName:"علي بن أبي طالب" },
  { id:69, name:"عيسى خليفة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1966-09-16", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:18, mosqueName:"الشاذولية" },
  { id:70, name:"بن حرزالله بن ثابت", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1970/11/08", education:"تاسعة أساسي", generation:"5", phone:"06 58 73 02 01", municipality:"الأغواط", mosqueId:42, mosqueName:"علي بن أبي طالب" },
  { id:71, name:"مزوزي كريمة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1990/04/14", education:"", generation:"", phone:"06 65 39 99 73", municipality:"الأغواط", mosqueId:26, mosqueName:"المدرسة القرآنية سماح" },
  { id:72, name:"صادقي خضرة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"09-07-1982", education:"جامعي", generation:"6", phone:"06 60 30 70 66", municipality:"الأغواط", mosqueId:21, mosqueName:"الصحوة" },
  { id:73, name:"آمنة سويسي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1984/05/10", education:"جامعي", generation:"3", phone:"06 68 44 13 73", municipality:"الأغواط", mosqueId:31, mosqueName:"حذيفة بن اليمان" },
  { id:74, name:"عياط خيرة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"07-06-1987", education:"ثالثة ثانوي", generation:"4", phone:"06 64 78 83 70", municipality:"الأغواط", mosqueId:6, mosqueName:"أسامة بن زيد" },
  { id:75, name:"تناح العطرة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1987/01/03", education:"جامعي", generation:"", phone:"06 98 60 66 27", municipality:"الاغواط", mosqueId:40, mosqueName:"عثمان بن عفان" },
  { id:76, name:"قرميط فاطمة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1978/02/03", education:"تقني سامي", generation:"4", phone:"06 67 44 84 65", municipality:"الأغواط", mosqueId:44, mosqueName:"فاطمة الزهراء" },
  { id:77, name:"سوفي آمنة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1984/12/06", education:"تقني", generation:"", phone:"06 57 88 52 17", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:78, name:"بن مغربي لحبيب", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1973-11-15", education:"9 اساسي", generation:"", phone:"", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:79, name:"محمد شطة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1981-02-14", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:7, mosqueName:"الأمير خالد" },
  { id:80, name:"حفصي سوسن", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1988/04/11", education:"جامعي", generation:"2", phone:"06 66 16 68 40", municipality:"الأغواط", mosqueId:44, mosqueName:"فاطمة الزهراء" },
  { id:81, name:"عبد القادر قاوي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1976/12/28", education:"ثالثة ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:19, mosqueName:"الشهداء" },
  { id:82, name:"جعمات سمية", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1992/03/11", education:"جامعي", generation:"", phone:"06 99 60 07 94", municipality:"الاغواط", mosqueId:43, mosqueName:"عمر بن الخطاب" },
  { id:83, name:"الحاج محمد قطيشة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1976-12-27", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:24, mosqueName:"الكبير" },
  { id:84, name:"بومدين هاجر", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1982/02/05", education:"جامعي", generation:"", phone:"06 57 03 26 93", municipality:"الاغواط", mosqueId:14, mosqueName:"الحسين" },
  { id:85, name:"لجدل خديجة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1989/01/30", education:"جامعي", generation:"3", phone:"06 99 18 05 55", municipality:"الأغواط", mosqueId:12, mosqueName:"البدر" },
  { id:86, name:"سويسي حميدات", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1966", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:34, mosqueName:"سيدنا حمزة" },
  { id:87, name:"جقيدل عائشة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1988/07/19", education:"جامعي", generation:"3", phone:"06 66 51 26 36", municipality:"الأغواط", mosqueId:31, mosqueName:"حذيفة بن اليمان" },
  { id:88, name:"جمال بلي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1970-01-13", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:45, mosqueName:"م.ق.سيدي عبد القادر الجيلالي" },
  { id:89, name:"إيمان بن التواتي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1989/10/22", education:"جامعي", generation:"2", phone:"06 66 18 60 32", municipality:"الأغواط", mosqueId:32, mosqueName:"زيد بن ثابت" },
  { id:90, name:"برارات اسماء", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1988/05/22", education:"جامعي", generation:"2", phone:"06 57 58 71 78", municipality:"الأغواط", mosqueId:16, mosqueName:"الرحمن" },
  { id:91, name:"حشاني هاجر", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1984/12/10", education:"تقني", generation:"", phone:"", municipality:"الاغواط", mosqueId:30, mosqueName:"جابر بن عبد الله" },
  { id:92, name:"خديجة بومكواز", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1984/09/03", education:"جامعي", generation:"6", phone:"06 68 00 53 77", municipality:"الأغواط", mosqueId:21, mosqueName:"الصحوة" },
  { id:93, name:"زواوي خيرة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1981/04/10", education:"تقني", generation:"5", phone:"06 57 07 74 94", municipality:"الأغواط", mosqueId:13, mosqueName:"البركة" },
  { id:94, name:"عزيز مراد", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1977-02-06", education:"", generation:"", phone:"", municipality:"الاغواط", mosqueId:21, mosqueName:"الصحوة" },
  { id:95, name:"محمد بوزيدي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1968", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:46, mosqueName:"مبارك الميلي" },
  { id:96, name:"خضرة قرميط", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1987/12/12", education:"", generation:"", phone:"06 64 21 72 91", municipality:"الأغواط", mosqueId:10, mosqueName:"الامام مسلم" },
  { id:97, name:"شريف عرارم", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1971-03-23", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"أبو بكر الصديق" },
  { id:98, name:"محمد السبع", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1959/01/23", education:"ثالثة ثانوي", generation:"2", phone:"06 73 98 87 89", municipality:"الأغواط", mosqueId:36, mosqueName:"سيدي عبد القادر جيلالي" },
  { id:99, name:"بن التواتي آسيا", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1988/07/03", education:"جامعي", generation:"3", phone:"06 98 90 95 22", municipality:"الاغواط", mosqueId:17, mosqueName:"الريان" },
  { id:100, name:"مبروك التخي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1969-07-26", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"المديرية" },
  { id:101, name:"شتوح بوعيشة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1978/02/08", education:"بكالوريا", generation:"6", phone:"", municipality:"الأغواط", mosqueId:5, mosqueName:"أحمد شطة" },
  { id:102, name:"تمزور أم الخير", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1987/6/18", education:"جامعي", generation:"3", phone:"06 65 73 11 07", municipality:"الاغواط", mosqueId:10, mosqueName:"الامام مسلم" },
  { id:103, name:"بن حمزة أم الخير", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1987/06/18", education:"", generation:"2", phone:"06 67 31 35 05", municipality:"الاغواط", mosqueId:49, mosqueName:"مصعب بن عمير" },
  { id:104, name:"يحي حاجي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1988-07-18", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:42, mosqueName:"علي بن أبي طالب" },
  { id:105, name:"بوزكري خديجة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1986/07/17", education:"جامعي", generation:"", phone:"06 69 88 57 20", municipality:"الاغواط", mosqueId:17, mosqueName:"الريان" },
  { id:106, name:"أمال بن فراح", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1985/04/03", education:"جامعي", generation:"3", phone:"", municipality:"الأغواط", mosqueId:6, mosqueName:"أسامة بن زيد" },
  { id:107, name:"كيرد عائشة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1984/10/24", education:"جامعي", generation:"5", phone:"06 64 62 32 32", municipality:"الاغواط", mosqueId:9, mosqueName:"الامام مالك" },
  { id:108, name:"مبروك السبع", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1975/01/23", education:"متوسط", generation:"1", phone:"06 62 50 60 26", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:109, name:"عبيرات امال", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1992/01/05", education:"جامعي", generation:"3", phone:"06 66 92 66 10", municipality:"الأغواط", mosqueId:17, mosqueName:"الريان" },
  { id:110, name:"عاشور ساعد", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1979-11-03", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:5, mosqueName:"أحمد شطة" },
  { id:111, name:"بلقاسم بن نوار", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1976/0301", education:"سنة 1 جامعي", generation:"", phone:"06 63 31 07 00", municipality:"الأغواط", mosqueId:39, mosqueName:"عبد الله بن عمر" },
  { id:112, name:"نعيجات عائشة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1984/06/04", education:"جامعي", generation:"2", phone:"06 66 08 28 83", municipality:"الأغواط", mosqueId:25, mosqueName:"الكوثر" },
  { id:113, name:"بن حرز الله حليمة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1989/10/08", education:"جامعي", generation:"3", phone:"06 98 99 41 46", municipality:"الأغواط", mosqueId:47, mosqueName:"مبروك كويسي" },
  { id:114, name:"بوعزيز سعاد", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1982/06/09", education:"بكالوريا", generation:"6", phone:"06 76 43 47 45", municipality:"الاغواط", mosqueId:5, mosqueName:"أحمد شطة" },
  { id:115, name:"محمد اسماعنية", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1973-10-02", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:47, mosqueName:"مبروك كويسي" },
  { id:116, name:"شقنان حنان", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"05-10-1991", education:"جامعي", generation:"2", phone:"06 99 78 81 40", municipality:"الأغواط", mosqueId:2, mosqueName:"أبو عبيدة الجراح" },
  { id:117, name:"اولاد العيد فاطمة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1981/06/26", education:"جامعي", generation:"2", phone:"06 57 81 81 03", municipality:"الاغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:118, name:"خديجة حنيشي", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1969-01-20", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:16, mosqueName:"الرحمن" },
  { id:119, name:"بن الدين مراد", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1971-08-01", education:"ثانوي", generation:"", phone:"06 67 15 44 49", municipality:"الأغواط", mosqueId:48, mosqueName:"مدرسة الشيخ محمد عزوز" },
  { id:120, name:"سميرة بوعزارة", rank:"أستاذ التعليم القرآني", role:"موظف", dob:"1989-08-21", education:"ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:23, mosqueName:"القدس" },
  { id:121, name:"محمد بهلولي", rank:"مؤذن", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:40, mosqueName:"عثمان بن عفان" },
  { id:122, name:"عبد القادر نابولسي", rank:"مؤذن", role:"موظف", dob:"1974-11-22", education:"", generation:"4", phone:"07 75 69 03 49", municipality:"الأغواط", mosqueId:35, mosqueName:"سيدي الشيخ" },
  { id:123, name:"أحمد ميلودية", rank:"مؤذن", role:"موظف", dob:"1980/09/14", education:"3 ثانوي", generation:"", phone:"06 57 74 42 51", municipality:"الأغواط", mosqueId:3, mosqueName:"أحمد بن حنبل" },
  { id:124, name:"خالد قفاف", rank:"مؤذن", role:"موظف", dob:"1977/08/26", education:"طور رابع", generation:"6", phone:"06 98 60 48 41", municipality:"الأغواط", mosqueId:4, mosqueName:"أحمد حماني" },
  { id:125, name:"عبد القادر قمقام", rank:"مؤذن", role:"موظف", dob:"1979/07/27", education:"", generation:"2", phone:"06 63 99 05 03", municipality:"الأغواط", mosqueId:25, mosqueName:"الكوثر" },
  { id:126, name:"مسعود العسري", rank:"مؤذن", role:"موظف", dob:"1968/12/14", education:"", generation:"3", phone:"06 69 74 54 12", municipality:"الاغواط", mosqueId:9, mosqueName:"الامام مالك" },
  { id:127, name:"مصطفى عبد اللاوي", rank:"مؤذن", role:"موظف", dob:"1988/04/18", education:"ثانية ثانوي", generation:"2", phone:"06 72 39 78 65", municipality:"الأغواط", mosqueId:22, mosqueName:"العتيق" },
  { id:128, name:"محمد بلاوي", rank:"مؤذن", role:"موظف", dob:"1955", education:"", generation:"11", phone:"06 75 92 89 75", municipality:"الأغواط", mosqueId:27, mosqueName:"النور(تاوتي)" },
  { id:129, name:"بشير طيبي", rank:"مؤذن", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:27, mosqueName:"النور(تاوتي)" },
  { id:130, name:"عطاء الله بن حرز الله", rank:"مؤذن", role:"موظف", dob:"1973-09-08", education:"متوسط", generation:"4", phone:"06 98 95 46 24", municipality:"الأغواط", mosqueId:8, mosqueName:"الأمير عبد القادر" },
  { id:131, name:"بن عزوز قطاف", rank:"مؤذن", role:"موظف", dob:"1975-12-10", education:"ثانوي", generation:"3", phone:"06 63 47 77 74", municipality:"الأغواط", mosqueId:14, mosqueName:"الحسين" },
  { id:132, name:"شبيرة هواري", rank:"مؤذن", role:"موظف", dob:"1979/06/10", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:16, mosqueName:"الرحمن" },
  { id:133, name:"محمد عبد الله", rank:"مؤذن", role:"موظف", dob:"1959/03/18", education:"متوسط", generation:"5", phone:"07 78 14 99 83", municipality:"الأغواط", mosqueId:7, mosqueName:"الأمير خالد" },
  { id:134, name:"عبد العزيز دبي", rank:"مؤذن", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:31, mosqueName:"حذيفة بن اليمان" },
  { id:135, name:"محمد خليفي", rank:"مؤذن", role:"موظف", dob:"", education:"", generation:"", phone:"06 62 58 27 01", municipality:"الأغواط", mosqueId:40, mosqueName:"عثمان بن عفان" },
  { id:136, name:"طالب الطيب", rank:"مؤذن", role:"موظف", dob:"1971/10/31", education:"تقني", generation:"3", phone:"06 72 37 00 97", municipality:"الأغواط", mosqueId:25, mosqueName:"الكوثر" },
  { id:137, name:"محمد الأمين عبد الحفيظي", rank:"مؤذن", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:19, mosqueName:"الشهداء" },
  { id:138, name:"عبد الرحمان ماحي", rank:"مؤذن", role:"موظف", dob:"1970/03/17", education:"", generation:"7", phone:"06 56 64 52 91", municipality:"الأغواط", mosqueId:51, mosqueName:"مصلى عقبة بن نافع" },
  { id:139, name:"عمر نحوي", rank:"مؤذن", role:"موظف", dob:"", education:"", generation:"2", phone:"06 72 64 97 07", municipality:"الأغواط", mosqueId:44, mosqueName:"فاطمة الزهراء" },
  { id:140, name:"أحمد لرقط", rank:"مؤذن", role:"موظف", dob:"1989/08/13", education:"ثانوي", generation:"1", phone:"06 73 23 57 16", municipality:"الأغواط", mosqueId:16, mosqueName:"الرحمن" },
  { id:141, name:"عبد العزيز شفار", rank:"مؤذن", role:"موظف", dob:"1976", education:"", generation:"", phone:"06 60 51 70 33", municipality:"الأغواط", mosqueId:43, mosqueName:"عمر بن الخطاب" },
  { id:142, name:"محمد بن عزوزي", rank:"مؤذن", role:"موظف", dob:"1988/08/02", education:"ثالثة ثانوي", generation:"//", phone:"06 76 65 29 15", municipality:"الأغواط", mosqueId:2, mosqueName:"أبو عبيدة الجراح" },
  { id:143, name:"محمد طاهري", rank:"مؤذن", role:"موظف", dob:"", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:9, mosqueName:"الامام مالك" },
  { id:144, name:"لخضر بن مسعود", rank:"مؤذن", role:"موظف", dob:"1978-01-06", education:"ثانية ثانوي", generation:"6", phone:"06 75 31 81 34", municipality:"الأغواط", mosqueId:22, mosqueName:"العتيق" },
  { id:145, name:"براهيم بوعكاز", rank:"مؤذن", role:"موظف", dob:"1971/06/28", education:"ثالثة ثانوي", generation:"4", phone:"07 82 48 09 29", municipality:"الأغواط", mosqueId:11, mosqueName:"الامير عبد القادر" },
  { id:146, name:"لغويني بوزكري", rank:"مؤذن", role:"موظف", dob:"1970/02/05", education:"رابعة متوسط", generation:"", phone:"06 60 29 70 75", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:147, name:"أحمد رحمون", rank:"مؤذن", role:"موظف", dob:"1969/03/29", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:15, mosqueName:"الخليفة" },
  { id:148, name:"لخضر طالب", rank:"مؤذن", role:"موظف", dob:"1975/04/28", education:"ثالثة ثانوي", generation:"3", phone:"06 68 52 01 92", municipality:"الأغواط", mosqueId:47, mosqueName:"مبروك كويسي" },
  { id:149, name:"أحمد التونسي", rank:"مؤذن", role:"موظف", dob:"1965/05/16", education:"ثالثة ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"المديرية" },
  { id:150, name:"عبد القادر دويدي", rank:"قيم", role:"موظف", dob:"1964/10/16", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:6, mosqueName:"أسامة بن زيد" },
  { id:151, name:"عيسى جرادي", rank:"قيم", role:"موظف", dob:"1968/01/25", education:"رابعة متوسط", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"المديرية" },
  { id:152, name:"بحطيطة ايهاب", rank:"قيم", role:"موظف", dob:"1994/05/06", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:15, mosqueName:"الخليفة" },
  { id:153, name:"محمد شارف", rank:"قيم", role:"موظف", dob:"1986/10/23", education:"ثالثة ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:10, mosqueName:"الامام مسلم" },
  { id:154, name:"بن جمالة مباركة", rank:"قيم", role:"موظف", dob:"27-09-1981", education:"", generation:"5", phone:"", municipality:"الأغواط", mosqueId:3, mosqueName:"أحمد بن حنبل" },
  { id:155, name:"يمينة قطاش", rank:"قيم", role:"موظف", dob:"1977/01/16", education:"جامعي", generation:"4", phone:"05 42 43 56 32", municipality:"الأغواط", mosqueId:25, mosqueName:"الكوثر" },
  { id:156, name:"قوال خالد", rank:"قيم", role:"موظف", dob:"1982/03/13", education:"ثالثة ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"أبو بكر الصديق" },
  { id:157, name:"أحمد صبة", rank:"قيم", role:"موظف", dob:"1980/09/28", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:50, mosqueName:"مصلى ابو هريرة" },
  { id:158, name:"محمدي صليحة", rank:"قيم", role:"موظف", dob:"1981/08/26", education:"تقني", generation:"4", phone:"06 57 78 04 06", municipality:"الأغواط", mosqueId:44, mosqueName:"فاطمة الزهراء" },
  { id:159, name:"قدور بهيز", rank:"قيم", role:"موظف", dob:"1984/09/16", education:"ثالثة ثانوي", generation:"", phone:"06 56 25 74 33", municipality:"الأغواط", mosqueId:43, mosqueName:"عمر بن الخطاب" },
  { id:160, name:"حليس هاجر", rank:"قيم", role:"موظف", dob:"1986/06/19", education:"", generation:"3", phone:"06 64 92 47 15", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:161, name:"اسماعيل مراد", rank:"قيم", role:"موظف", dob:"1984/12/15", education:"ثالثة ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"أبو بكر الصديق" },
  { id:162, name:"مبارك حدباوي", rank:"قيم", role:"موظف", dob:"1973/05/12", education:"", generation:"", phone:"", municipality:"الأغواط", mosqueId:1, mosqueName:"المديرية" },
  { id:163, name:"فرشان فوزية", rank:"قيم", role:"موظف", dob:"07-08-1987", education:"", generation:"", phone:"06 69 87 48 77", municipality:"الأغواط", mosqueId:17, mosqueName:"الريان" },
  { id:164, name:"علي مليك", rank:"قيم", role:"موظف", dob:"1979/11/01", education:"ثالثة ثانوي", generation:"", phone:"", municipality:"الأغواط", mosqueId:41, mosqueName:"عقبة بن نافع" },
  { id:165, name:"جهاد بن جعيد", rank:"قيم", role:"موظف", dob:"1989/11/05", education:"ثالثة ثانوي", generation:"2", phone:"06 99 63 34 44", municipality:"الأغواط", mosqueId:29, mosqueName:"بلال بن رباح" },
  { id:166, name:"غزال حمزة", rank:"قيم", role:"موظف", dob:"1981/10/31", education:"ثالثة ثانوي", generation:"1", phone:"06 98  76 90 73", municipality:"الأغواط", mosqueId:36, mosqueName:"سيدي عبد القادر جيلالي" },
  { id:167, name:"سمية فروج", rank:"قيم", role:"موظف", dob:"1986/12/08", education:"جامعي", generation:"", phone:"", municipality:"الأغواط", mosqueId:21, mosqueName:"الصحوة" },
  { id:168, name:"عمر مراد", rank:"قيم", role:"موظف", dob:"1986/1/11", education:"", generation:"", phone:"06 56 07 81 33", municipality:"الأغواط", mosqueId:29, mosqueName:"بلال بن رباح" },
  { id:169, name:"لعمش مارية", rank:"قيم", role:"موظف", dob:"1983/07/26", education:"تقني", generation:"2", phone:"06 62 60 80 05", municipality:"الأغواط", mosqueId:14, mosqueName:"الحسين" },
  { id:170, name:"عيسى نور الدين", rank:"قيم", role:"موظف", dob:"1991/06/08", education:"تقني", generation:"", phone:"", municipality:"الأغواط", mosqueId:20, mosqueName:"الشيخ البشير الابراهيمي" },
];

export const students: Student[] = [
  { id:9,  name:"رميصاء بساس",    fatherName:"رابح",       dob:"2013/05/22", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"يس",       part:"ربع",  grade:"جيد",   progress:72 },
  { id:10, name:"ليلى مريزقي",    fatherName:"عبدالقادر",  dob:"2013/07/31", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"سبأ",      part:"ثمن",  grade:"ممتاز", progress:85 },
  { id:11, name:"فاطمة مريزقي",   fatherName:"عبدالقادر",  dob:"2015/09/06", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"محمد",     part:"ربع",  grade:"جيد",   progress:68 },
  { id:12, name:"خديجة بساس",     fatherName:"حميدة",      dob:"2013/10/17", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"محمد",     part:"نصف",  grade:"ممتاز", progress:90 },
  { id:13, name:"عفاف مريزقي",    fatherName:"عبدالقادر",  dob:"2019/09/09", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الحديد",   part:"ثمن",  grade:"جيد",   progress:55 },
  { id:14, name:"خديجة بساس",     fatherName:"رابح",       dob:"2019/07/17", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"المطففين", part:"ثمن",  grade:"جيد",   progress:50 },
  { id:15, name:"ام الخير حميدات",fatherName:"بشير",       dob:"2019/06/25", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الملك",    part:"ثمن",  grade:"متوسط", progress:45 },
  { id:16, name:"مرية بساس",      fatherName:"نورالدين",   dob:"2019/01/08", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"النازعات", part:"ثمن",  grade:"جيد",   progress:60 },
  { id:17, name:"فاطمة جيدل",     fatherName:"عبدالقادر",  dob:"2020/01/15", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الحشر",    part:"ثمن",  grade:"ممتاز", progress:78 },
  { id:18, name:"رفيدة حميدات",   fatherName:"محمد",       dob:"2020/05/22", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"المطففين", part:"ثمن",  grade:"جيد",   progress:48 },
  { id:19, name:"اسراء بيران",    fatherName:"محمد",       dob:"2016/08/16", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الذاريات", part:"ربع",  grade:"ممتاز", progress:82 },
  { id:20, name:"وسام صحراوي",    fatherName:"محمد",       dob:"2019/10/26", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"البروج",   part:"ثمن",  grade:"جيد",   progress:52 },
  { id:21, name:"الاء بن سعدة",   fatherName:"علي",        dob:"2017/09/04", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الانسان",  part:"ثمن",  grade:"متوسط", progress:42 },
  { id:22, name:"ريتاج بيران",    fatherName:"محمد",       dob:"2020/04/05", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الغاشية",  part:"ثمن",  grade:"جيد",   progress:58 },
  { id:23, name:"سرين بن سعدة",   fatherName:"عزيز",       dob:"2017/11/19", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"القيامة",  part:"ثمن",  grade:"جيد",   progress:63 },
  { id:24, name:"اماني بساس",     fatherName:"نورالدين",   dob:"2020/12/08", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"البينة",   part:"ثمن",  grade:"ممتاز", progress:75 },
  { id:25, name:"كوثر بساس",      fatherName:"حميدة",      dob:"2021/11/13", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الماعون",  part:"ثمن",  grade:"جيد",   progress:47 },
  { id:26, name:"دلال شقنان",     fatherName:"علي",        dob:"2016",       gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الانشقاق", part:"ربع",  grade:"جيد",   progress:65 },
  { id:27, name:"مسعودة قصاص",    fatherName:"ميود",       dob:"",           gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الماعون",  part:"ثمن",  grade:"متوسط", progress:40 },
  { id:28, name:"ايمان تقاري",    fatherName:"الناصر",     dob:"2014/09/11", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"القمر",    part:"نصف",  grade:"ممتاز", progress:88 },
  { id:29, name:"اريج قربة",      fatherName:"خالد",       dob:"2015/01/27", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الطلاق",   part:"ربع",  grade:"جيد",   progress:70 },
  { id:30, name:"رقية قربة",      fatherName:"خالد",       dob:"2016/08/17", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"المرسلات", part:"ربع",  grade:"جيد",   progress:67 },
  { id:31, name:"زهرة مشراوي",    fatherName:"وليد",       dob:"2018/04/02", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"العاديات", part:"ثمن",  grade:"جيد",   progress:53 },
  { id:32, name:"فطوم مشراوي",    fatherName:"وليد",       dob:"2020/10/25", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"المسد",    part:"ثمن",  grade:"جيد",   progress:44 },
  { id:33, name:"مريم بتول ماحي", fatherName:"محمد",       dob:"2017/12/06", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"الليل",    part:"ثمن",  grade:"متوسط", progress:38 },
  { id:34, name:"رتيل ماحي",      fatherName:"محمد",       dob:"2019/12/08", gender:"أنثى", teacherId:68, teacherName:"حليمة السعدية معيلب", mosqueId:42, mosqueName:"علي بن أبي طالب", surah:"العاديات", part:"ثمن",  grade:"جيد",   progress:56 },
];

export const schedules = [
  { id:1, teacherId:1, teacherName:"بلقاسم جيلاني", mosqueId:6, mosqueName:"أسامة بن زيد", day:"الاحد", startTime:"14:00", endTime:"16:00" },
  { id:2, teacherId:2, teacherName:"عبد القادر كيرد", mosqueId:3, mosqueName:"أحمد حماني", day:"الاحد", startTime:"15:00", endTime:"17:00" },
  { id:3, teacherId:3, teacherName:"قويدر مرزوقي", mosqueId:12, mosqueName:"الكوثر", day:"الاثنين", startTime:"14:00", endTime:"16:00" },
  { id:4, teacherId:4, teacherName:"قويدر ميلودية", mosqueId:4, mosqueName:"أحمد شطة", day:"الثلاثاء", startTime:"10:00", endTime:"12:00" },
  { id:5, teacherId:5, teacherName:"سعيد بن مويزة", mosqueId:22, mosqueName:"القدس", day:"الاربعاء", startTime:"15:00", endTime:"17:00" },
  { id:6, teacherId:6, teacherName:"عبد الباقي عبد الباقي", mosqueId:10, mosqueName:"الامام مالك", day:"الخميس", startTime:"14:00", endTime:"16:00" },
  { id:7, teacherId:1, teacherName:"بلقاسم جيلاني", mosqueId:6, mosqueName:"أسامة بن زيد", day:"الخميس", startTime:"14:00", endTime:"16:00" },
  { id:8, teacherId:7, teacherName:"عبد القادر بوزيد", mosqueId:36, mosqueName:"زيد بن ثابت", day:"السبت", startTime:"10:00", endTime:"12:00" },
  { id:9, teacherId:9, teacherName:"ياسين صادقي", mosqueId:9, mosqueName:"الامام مسلم", day:"الاثنين", startTime:"08:00", endTime:"10:00" },
  { id:10, teacherId:2, teacherName:"عبد القادر كيرد", mosqueId:3, mosqueName:"أحمد حماني", day:"السبت", startTime:"14:00", endTime:"16:00" },
];

export const users = [
  // ── المسؤول ──
  { id:1, username:"admin", password:"admin123", role:"admin", name:"المسؤول العام" },
  // ── أولياء الأمور ──
  { id:201, username:"wali01", password:"wali012024", role:"guardian", name:"ولي أمر ايمان تقاري",             studentIds:[28]         },
  { id:202, username:"wali02", password:"wali022024", role:"guardian", name:"ولي أمر ام الخير حميدات",         studentIds:[15]         },
  { id:203, username:"wali03", password:"wali032024", role:"guardian", name:"ولي أمر  بساس - حميدة",       studentIds:[12,25]      },
  { id:204, username:"wali04", password:"wali042024", role:"guardian", name:"ولي أمر  قربة - خالد",        studentIds:[29,30]      },
  { id:205, username:"wali05", password:"wali052024", role:"guardian", name:"ولي أمر  بساس - رابح",        studentIds:[9,14]       },
  { id:206, username:"wali06", password:"wali062024", role:"guardian", name:"ولي أمر فاطمة جيدل",              studentIds:[17]         },
  { id:207, username:"wali07", password:"wali072024", role:"guardian", name:"ولي أمر  مريزقي - عبدالقادر", studentIds:[10,11,13]   },
  { id:208, username:"wali08", password:"wali082024", role:"guardian", name:"ولي أمر سرين بن سعدة",            studentIds:[23]         },
  { id:209, username:"wali09", password:"wali092024", role:"guardian", name:"ولي أمر الاء بن سعدة",            studentIds:[21]         },
  { id:210, username:"wali10", password:"wali102024", role:"guardian", name:"ولي أمر دلال شقنان",              studentIds:[26]         },
  { id:211, username:"wali11", password:"wali112024", role:"guardian", name:"ولي أمر  بيران - محمد",       studentIds:[19,22]      },
  { id:212, username:"wali12", password:"wali122024", role:"guardian", name:"ولي أمر رفيدة حميدات",            studentIds:[18]         },
  { id:213, username:"wali13", password:"wali132024", role:"guardian", name:"ولي أمر وسام صحراوي",             studentIds:[20]         },
  { id:214, username:"wali14", password:"wali142024", role:"guardian", name:"ولي أمر  ماحي - محمد",        studentIds:[33,34]      },
  { id:215, username:"wali15", password:"wali152024", role:"guardian", name:"ولي أمر مسعودة قصاص",             studentIds:[27]         },
  { id:216, username:"wali16", password:"wali162024", role:"guardian", name:"ولي أمر  بساس - نورالدين",    studentIds:[16,24]      },
  { id:217, username:"wali17", password:"wali172024", role:"guardian", name:"ولي أمر  مشراوي - وليد",      studentIds:[31,32]      },
  // ── المؤطرون (username = first.family | password = pass123) ──
  { id:1001, username:"m.larwsy", password:"pass123", role:"teacher", name:"محمد الأخضر لعروسي", teacherId:1 },
  { id:1002, username:"b.jylany", password:"pass123", role:"teacher", name:"بلقاسم جيلاني", teacherId:2 },
  { id:1003, username:"a.kyrd", password:"pass123", role:"teacher", name:"عبد القادر كيرد", teacherId:3 },
  { id:1004, username:"s.aldhyb", password:"pass123", role:"teacher", name:"صفي الدين الذيب", teacherId:4 },
  { id:1005, username:"a.jdo", password:"pass123", role:"teacher", name:"عبد السلام بن جدو", teacherId:5 },
  { id:1006, username:"a.alhfyzy", password:"pass123", role:"teacher", name:"الأخضر عبد الحفيظي", teacherId:6 },
  { id:1007, username:"a.mhmdy", password:"pass123", role:"teacher", name:"عمر محمدي", teacherId:7 },
  { id:1008, username:"q.mrzwqy", password:"pass123", role:"teacher", name:"قويدر مرزوقي", teacherId:8 },
  { id:1009, username:"q.mylwdya", password:"pass123", role:"teacher", name:"قويدر ميلودية", teacherId:9 },
  { id:1010, username:"s.mwyza", password:"pass123", role:"teacher", name:"سعيد بن مويزة", teacherId:10 },
  { id:1011, username:"a.albaqy", password:"pass123", role:"teacher", name:"عبد الباقي عبد الباقي", teacherId:11 },
  { id:1012, username:"a.bwzyd", password:"pass123", role:"teacher", name:"عبد القادر بوزيد", teacherId:12 },
  { id:1013, username:"y.sadqy", password:"pass123", role:"teacher", name:"ياسين صادقي", teacherId:13 },
  { id:1014, username:"a.mwsly", password:"pass123", role:"teacher", name:"العربي موسلي", teacherId:14 },
  { id:1015, username:"a.fntazy", password:"pass123", role:"teacher", name:"احمد  فنطازي", teacherId:15 },
  { id:1016, username:"a.ghwyrq", password:"pass123", role:"teacher", name:"العلمي غويرق", teacherId:16 },
  { id:1017, username:"a.bsas", password:"pass123", role:"teacher", name:"علي  بساس", teacherId:17 },
  { id:1018, username:"j.aajb", password:"pass123", role:"teacher", name:"جلول عاجب", teacherId:18 },
  { id:1019, username:"m.shlawshy", password:"pass123", role:"teacher", name:"منذر شلاوشي", teacherId:19 },
  { id:1020, username:"a.kady", password:"pass123", role:"teacher", name:"عبد اللطيف كادي", teacherId:20 },
  { id:1021, username:"a.rzyqy", password:"pass123", role:"teacher", name:"عبد القادر رزيقي", teacherId:21 },
  { id:1022, username:"m.qhqwhy", password:"pass123", role:"teacher", name:"محمد قحقوحي", teacherId:22 },
  { id:1023, username:"m.bayt", password:"pass123", role:"teacher", name:"مختار بعيط", teacherId:23 },
  { id:1024, username:"n.qmyty", password:"pass123", role:"teacher", name:"نصر الدين  قميتي", teacherId:24 },
  { id:1025, username:"s.baytysh", password:"pass123", role:"teacher", name:"سعد بعيطيش", teacherId:25 },
  { id:1026, username:"a.madwy", password:"pass123", role:"teacher", name:"عبد الفتاح ماضوي", teacherId:26 },
  { id:1027, username:"y.msawdy", password:"pass123", role:"teacher", name:"يوسف مسعودي", teacherId:27 },
  { id:1028, username:"y.ghwyrq", password:"pass123", role:"teacher", name:"يحيى غويرق", teacherId:28 },
  { id:1029, username:"a.khllsh", password:"pass123", role:"teacher", name:"العيد كحللش", teacherId:29 },
  { id:1030, username:"m.blmghrby", password:"pass123", role:"teacher", name:"مصطفى بلمغربي", teacherId:30 },
  { id:1031, username:"l.tyfwry", password:"pass123", role:"teacher", name:"لحسن طيفوري", teacherId:31 },
  { id:1032, username:"n.bdrany", password:"pass123", role:"teacher", name:"نفيسة بدراني", teacherId:32 },
  { id:1033, username:"m.khnafyf", password:"pass123", role:"teacher", name:"مفيدة خنافيف", teacherId:33 },
  { id:1034, username:"s.rhal", password:"pass123", role:"teacher", name:"سمية بن رحال", teacherId:34 },
  { id:1035, username:"d.ghrby", password:"pass123", role:"teacher", name:"دلال بن غربي", teacherId:35 },
  { id:1036, username:"b.mrym", password:"pass123", role:"teacher", name:"بن مويزة مريم", teacherId:36 },
  { id:1037, username:"k.amyna", password:"pass123", role:"teacher", name:"كعبوش  أمينة", teacherId:37 },
  { id:1038, username:"r.ljdl", password:"pass123", role:"teacher", name:"رميصاء لجدل", teacherId:38 },
  { id:1039, username:"b.nayma", password:"pass123", role:"teacher", name:"بونيف نعيمة", teacherId:39 },
  { id:1040, username:"b.marya", password:"pass123", role:"teacher", name:"بساس مارية", teacherId:40 },
  { id:1041, username:"b.asya", password:"pass123", role:"teacher", name:"بساس أسيا", teacherId:41 },
  { id:1042, username:"b.hlyma", password:"pass123", role:"teacher", name:"بعيط حليمة", teacherId:42 },
  { id:1043, username:"a.alzhra", password:"pass123", role:"teacher", name:"عرارم فاطمة الزهراء", teacherId:43 },
  { id:1044, username:"f.zbyda", password:"pass123", role:"teacher", name:"فداق زبيدة", teacherId:44 },
  { id:1045, username:"b.sna", password:"pass123", role:"teacher", name:"بن السايح سناء", teacherId:45 },
  { id:1046, username:"h.hsna", password:"pass123", role:"teacher", name:"همكة حنان حسناء", teacherId:46 },
  { id:1047, username:"s.sbty", password:"pass123", role:"teacher", name:"سعيد سبطي", teacherId:47 },
  { id:1048, username:"a.khtwy", password:"pass123", role:"teacher", name:"أحمد خطوي", teacherId:48 },
  { id:1049, username:"a.rnan", password:"pass123", role:"teacher", name:"إسماعيل رنان", teacherId:49 },
  { id:1050, username:"a.alnya", password:"pass123", role:"teacher", name:"أحمد النية", teacherId:50 },
  { id:1051, username:"a.bwqrara", password:"pass123", role:"teacher", name:"الجيلالي بوقرارة", teacherId:51 },
  { id:1052, username:"m.shnwfy", password:"pass123", role:"teacher", name:"محمد شنوفي", teacherId:52 },
  { id:1053, username:"b.bwlrbah", password:"pass123", role:"teacher", name:"بن غريقة بولرباح", teacherId:53 },
  { id:1054, username:"m.hmdy", password:"pass123", role:"teacher", name:"معمر حمدي", teacherId:54 },
  { id:1055, username:"a.ararm", password:"pass123", role:"teacher", name:"عيسى عرارم", teacherId:55 },
  { id:1056, username:"l.lmnwr", password:"pass123", role:"teacher", name:"لحبيب لمنور", teacherId:56 },
  { id:1057, username:"a.shlaby", password:"pass123", role:"teacher", name:"الحاج شلابي", teacherId:57 },
  { id:1058, username:"a.bwlnwar", password:"pass123", role:"teacher", name:"عبد الحفيظي بولنوار", teacherId:58 },
  { id:1059, username:"t.alamyn", password:"pass123", role:"teacher", name:"تناح الأمين", teacherId:59 },
  { id:1060, username:"t.twaty", password:"pass123", role:"teacher", name:"تواتي بن تواتي", teacherId:60 },
  { id:1061, username:"b.ywsf", password:"pass123", role:"teacher", name:"بن نيش يوسف", teacherId:61 },
  { id:1062, username:"a.aljwdy", password:"pass123", role:"teacher", name:"عطاءالله الجودي", teacherId:62 },
  { id:1063, username:"b.jdw", password:"pass123", role:"teacher", name:"بن حرزالله بن جدو", teacherId:63 },
  { id:1064, username:"m.blhwt", password:"pass123", role:"teacher", name:"مبروك بلحوت", teacherId:64 },
  { id:1065, username:"kh.hmka", password:"pass123", role:"teacher", name:"خالد همكة", teacherId:65 },
  { id:1066, username:"a.arzyqy", password:"pass123", role:"teacher", name:"الحاج ارزيقي", teacherId:66 },
  { id:1067, username:"a.allh", password:"pass123", role:"teacher", name:"عبد الحميد رزق الله", teacherId:67 },
  { id:1068, username:"h.maylb", password:"pass123", role:"teacher", name:"حليمة السعدية معيلب", teacherId:68 },
  { id:1069, username:"a.khlyfa", password:"pass123", role:"teacher", name:"عيسى خليفة", teacherId:69 },
  { id:1070, username:"b.thabt", password:"pass123", role:"teacher", name:"بن حرزالله بن ثابت", teacherId:70 },
  { id:1071, username:"m.kryma", password:"pass123", role:"teacher", name:"مزوزي كريمة", teacherId:71 },
  { id:1072, username:"s.khdra", password:"pass123", role:"teacher", name:"صادقي خضرة", teacherId:72 },
  { id:1073, username:"a.swysy", password:"pass123", role:"teacher", name:"آمنة سويسي", teacherId:73 },
  { id:1074, username:"a.khyra", password:"pass123", role:"teacher", name:"عياط خيرة", teacherId:74 },
  { id:1075, username:"t.alatra", password:"pass123", role:"teacher", name:"تناح العطرة", teacherId:75 },
  { id:1076, username:"q.fatma", password:"pass123", role:"teacher", name:"قرميط فاطمة", teacherId:76 },
  { id:1077, username:"s.amna", password:"pass123", role:"teacher", name:"سوفي آمنة", teacherId:77 },
  { id:1078, username:"b.lhbyb", password:"pass123", role:"teacher", name:"بن مغربي لحبيب", teacherId:78 },
  { id:1079, username:"m.shta", password:"pass123", role:"teacher", name:"محمد شطة", teacherId:79 },
  { id:1080, username:"h.swsn", password:"pass123", role:"teacher", name:"حفصي سوسن", teacherId:80 },
  { id:1081, username:"a.qawy", password:"pass123", role:"teacher", name:"عبد القادر قاوي", teacherId:81 },
  { id:1082, username:"j.smya", password:"pass123", role:"teacher", name:"جعمات سمية", teacherId:82 },
  { id:1083, username:"a.qtysha", password:"pass123", role:"teacher", name:"الحاج محمد قطيشة", teacherId:83 },
  { id:1084, username:"b.hajr", password:"pass123", role:"teacher", name:"بومدين هاجر", teacherId:84 },
  { id:1085, username:"l.khdyja", password:"pass123", role:"teacher", name:"لجدل خديجة", teacherId:85 },
  { id:1086, username:"s.hmydat", password:"pass123", role:"teacher", name:"سويسي حميدات", teacherId:86 },
  { id:1087, username:"j.aaysha", password:"pass123", role:"teacher", name:"جقيدل عائشة", teacherId:87 },
  { id:1088, username:"j.bly", password:"pass123", role:"teacher", name:"جمال بلي", teacherId:88 },
  { id:1089, username:"a.altwaty", password:"pass123", role:"teacher", name:"إيمان بن التواتي", teacherId:89 },
  { id:1090, username:"b.asma", password:"pass123", role:"teacher", name:"برارات اسماء", teacherId:90 },
  { id:1091, username:"h.hajr", password:"pass123", role:"teacher", name:"حشاني هاجر", teacherId:91 },
  { id:1092, username:"kh.bwmkwaz", password:"pass123", role:"teacher", name:"خديجة بومكواز", teacherId:92 },
  { id:1093, username:"z.khyra", password:"pass123", role:"teacher", name:"زواوي خيرة", teacherId:93 },
  { id:1094, username:"a.mrad", password:"pass123", role:"teacher", name:"عزيز مراد", teacherId:94 },
  { id:1095, username:"m.bwzydy", password:"pass123", role:"teacher", name:"محمد بوزيدي", teacherId:95 },
  { id:1096, username:"kh.qrmyt", password:"pass123", role:"teacher", name:"خضرة قرميط", teacherId:96 },
  { id:1097, username:"sh.ararm", password:"pass123", role:"teacher", name:"شريف عرارم", teacherId:97 },
  { id:1098, username:"m.alsba", password:"pass123", role:"teacher", name:"محمد السبع", teacherId:98 },
  { id:1099, username:"b.asya1", password:"pass123", role:"teacher", name:"بن التواتي آسيا", teacherId:99 },
  { id:1100, username:"m.altkhy", password:"pass123", role:"teacher", name:"مبروك التخي", teacherId:100 },
  { id:1101, username:"sh.bwaysha", password:"pass123", role:"teacher", name:"شتوح بوعيشة", teacherId:101 },
  { id:1102, username:"t.alkhyr", password:"pass123", role:"teacher", name:"تمزور أم الخير", teacherId:102 },
  { id:1103, username:"b.alkhyr", password:"pass123", role:"teacher", name:"بن حمزة أم الخير", teacherId:103 },
  { id:1104, username:"y.hajy", password:"pass123", role:"teacher", name:"يحي حاجي", teacherId:104 },
  { id:1105, username:"b.khdyja", password:"pass123", role:"teacher", name:"بوزكري خديجة", teacherId:105 },
  { id:1106, username:"a.frah", password:"pass123", role:"teacher", name:"أمال بن فراح", teacherId:106 },
  { id:1107, username:"k.aaysha", password:"pass123", role:"teacher", name:"كيرد عائشة", teacherId:107 },
  { id:1108, username:"m.alsba1", password:"pass123", role:"teacher", name:"مبروك السبع", teacherId:108 },
  { id:1109, username:"a.amal", password:"pass123", role:"teacher", name:"عبيرات امال", teacherId:109 },
  { id:1110, username:"a.saad", password:"pass123", role:"teacher", name:"عاشور ساعد", teacherId:110 },
  { id:1111, username:"b.nwar", password:"pass123", role:"teacher", name:"بلقاسم بن نوار", teacherId:111 },
  { id:1112, username:"n.aaysha", password:"pass123", role:"teacher", name:"نعيجات عائشة", teacherId:112 },
  { id:1113, username:"b.hlyma1", password:"pass123", role:"teacher", name:"بن حرز الله حليمة", teacherId:113 },
  { id:1114, username:"b.saad", password:"pass123", role:"teacher", name:"بوعزيز سعاد", teacherId:114 },
  { id:1115, username:"m.asmaanya", password:"pass123", role:"teacher", name:"محمد اسماعنية", teacherId:115 },
  { id:1116, username:"sh.hnan", password:"pass123", role:"teacher", name:"شقنان حنان", teacherId:116 },
  { id:1117, username:"a.fatma", password:"pass123", role:"teacher", name:"اولاد العيد فاطمة", teacherId:117 },
  { id:1118, username:"kh.hnyshy", password:"pass123", role:"teacher", name:"خديجة حنيشي", teacherId:118 },
  { id:1119, username:"b.mrad", password:"pass123", role:"teacher", name:"بن الدين مراد", teacherId:119 },
  { id:1120, username:"s.bwazara", password:"pass123", role:"teacher", name:"سميرة بوعزارة", teacherId:120 },
  { id:1121, username:"m.bhlwly", password:"pass123", role:"teacher", name:"محمد بهلولي", teacherId:121 },
  { id:1122, username:"a.nabwlsy", password:"pass123", role:"teacher", name:"عبد القادر نابولسي", teacherId:122 },
  { id:1123, username:"a.mylwdya", password:"pass123", role:"teacher", name:"أحمد ميلودية", teacherId:123 },
  { id:1124, username:"kh.qfaf", password:"pass123", role:"teacher", name:"خالد قفاف", teacherId:124 },
  { id:1125, username:"a.qmqam", password:"pass123", role:"teacher", name:"عبد القادر قمقام", teacherId:125 },
  { id:1126, username:"m.alasry", password:"pass123", role:"teacher", name:"مسعود العسري", teacherId:126 },
  { id:1127, username:"m.allawy", password:"pass123", role:"teacher", name:"مصطفى عبد اللاوي", teacherId:127 },
  { id:1128, username:"m.blawy", password:"pass123", role:"teacher", name:"محمد بلاوي", teacherId:128 },
  { id:1129, username:"b.tyby", password:"pass123", role:"teacher", name:"بشير طيبي", teacherId:129 },
  { id:1130, username:"a.allh1", password:"pass123", role:"teacher", name:"عطاء الله بن حرز الله", teacherId:130 },
  { id:1131, username:"b.qtaf", password:"pass123", role:"teacher", name:"بن عزوز قطاف", teacherId:131 },
  { id:1132, username:"sh.hwary", password:"pass123", role:"teacher", name:"شبيرة هواري", teacherId:132 },
  { id:1133, username:"m.allh", password:"pass123", role:"teacher", name:"محمد عبد الله", teacherId:133 },
  { id:1134, username:"a.dby", password:"pass123", role:"teacher", name:"عبد العزيز دبي", teacherId:134 },
  { id:1135, username:"m.khlyfy", password:"pass123", role:"teacher", name:"محمد خليفي", teacherId:135 },
  { id:1136, username:"t.altyb", password:"pass123", role:"teacher", name:"طالب الطيب", teacherId:136 },
  { id:1137, username:"m.alhfyzy", password:"pass123", role:"teacher", name:"محمد الأمين عبد الحفيظي", teacherId:137 },
  { id:1138, username:"a.mahy", password:"pass123", role:"teacher", name:"عبد الرحمان ماحي", teacherId:138 },
  { id:1139, username:"a.nhwy", password:"pass123", role:"teacher", name:"عمر نحوي", teacherId:139 },
  { id:1140, username:"a.lrqt", password:"pass123", role:"teacher", name:"أحمد لرقط", teacherId:140 },
  { id:1141, username:"a.shfar", password:"pass123", role:"teacher", name:"عبد العزيز شفار", teacherId:141 },
  { id:1142, username:"m.azwzy", password:"pass123", role:"teacher", name:"محمد بن عزوزي", teacherId:142 },
  { id:1143, username:"m.tahry", password:"pass123", role:"teacher", name:"محمد طاهري", teacherId:143 },
  { id:1144, username:"l.msawd", password:"pass123", role:"teacher", name:"لخضر بن مسعود", teacherId:144 },
  { id:1145, username:"b.bwakaz", password:"pass123", role:"teacher", name:"براهيم بوعكاز", teacherId:145 },
  { id:1146, username:"l.bwzkry", password:"pass123", role:"teacher", name:"لغويني بوزكري", teacherId:146 },
  { id:1147, username:"a.rhmwn", password:"pass123", role:"teacher", name:"أحمد رحمون", teacherId:147 },
  { id:1148, username:"l.talb", password:"pass123", role:"teacher", name:"لخضر طالب", teacherId:148 },
  { id:1149, username:"a.altwnsy", password:"pass123", role:"teacher", name:"أحمد التونسي", teacherId:149 },
  { id:1150, username:"a.dwydy", password:"pass123", role:"teacher", name:"عبد القادر دويدي", teacherId:150 },
  { id:1151, username:"a.jrady", password:"pass123", role:"teacher", name:"عيسى جرادي", teacherId:151 },
  { id:1152, username:"b.ayhab", password:"pass123", role:"teacher", name:"بحطيطة ايهاب", teacherId:152 },
  { id:1153, username:"m.sharf", password:"pass123", role:"teacher", name:"محمد شارف", teacherId:153 },
  { id:1154, username:"b.mbarka", password:"pass123", role:"teacher", name:"بن جمالة مباركة", teacherId:154 },
  { id:1155, username:"y.qtash", password:"pass123", role:"teacher", name:"يمينة قطاش", teacherId:155 },
  { id:1156, username:"q.khald", password:"pass123", role:"teacher", name:"قوال خالد", teacherId:156 },
  { id:1157, username:"a.sba", password:"pass123", role:"teacher", name:"أحمد صبة", teacherId:157 },
  { id:1158, username:"m.slyha", password:"pass123", role:"teacher", name:"محمدي صليحة", teacherId:158 },
  { id:1159, username:"q.bhyz", password:"pass123", role:"teacher", name:"قدور بهيز", teacherId:159 },
  { id:1160, username:"h.hajr1", password:"pass123", role:"teacher", name:"حليس هاجر", teacherId:160 },
  { id:1161, username:"a.mrad1", password:"pass123", role:"teacher", name:"اسماعيل مراد", teacherId:161 },
  { id:1162, username:"m.hdbawy", password:"pass123", role:"teacher", name:"مبارك حدباوي", teacherId:162 },
  { id:1163, username:"f.fwzya", password:"pass123", role:"teacher", name:"فرشان فوزية", teacherId:163 },
  { id:1164, username:"a.mlyk", password:"pass123", role:"teacher", name:"علي مليك", teacherId:164 },
  { id:1165, username:"j.jayd", password:"pass123", role:"teacher", name:"جهاد بن جعيد", teacherId:165 },
  { id:1166, username:"gh.hmza", password:"pass123", role:"teacher", name:"غزال حمزة", teacherId:166 },
  { id:1167, username:"s.frwj", password:"pass123", role:"teacher", name:"سمية فروج", teacherId:167 },
  { id:1168, username:"a.mrad2", password:"pass123", role:"teacher", name:"عمر مراد", teacherId:168 },
  { id:1169, username:"l.marya", password:"pass123", role:"teacher", name:"لعمش مارية", teacherId:169 },
  { id:1170, username:"a.aldyn", password:"pass123", role:"teacher", name:"عيسى نور الدين", teacherId:170 },
];